In [6]:
import numpy as np


## __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;                          
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;                         
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;                           
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.    


   а)$AB$ нельзя, $BA$ нельзя
    
   б)$AB$ можно 2 x 3, $BA$ нельзя
    
   в)$AB$ можно 8 x 8, $BA$ можно 3 x 3
    
   г)$AB$ можно 4 x 4, $BA$ можно 4 x 4

## __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [13]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [17]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [15]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

## __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

## __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [24]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [27]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [28]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

##  __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [45]:
def dot(a, b):
    
    def sum_(firs, sec):
        
        if len(firs) == len(sec):
            sum_q = 0
            for i in range(len(firs)):
                sum_q += firs[i] * sec[i]
        
        return sum_q
        
    dot_ = np.zeros(shape=(a.shape[0], b.shape[1]))
    for row in range(dot_.shape[0]):
        for column in range(dot_.shape[1]):
            dot_[row][column] = sum_(a[row], b[:,column])
    
    return dot_

In [46]:
dot(A, A.T)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [44]:
dot(A.T, A)

array([[45.,  0.],
       [ 0., 14.]])